title: Christina Pilip
description: Portfolio and projects
baseurl: ""
url: "https://cpilip.github.io"

plugins:
  - jekyll-feed

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

collections_dir: collections

defaults:
  - scope:
      path: ""
    values:
      layout: default